# Taalcursus - woordenlijsten per taal - Created by DieOuwe · www.dieouwe.nl
# Elke taal: 42 woorden in dezelfde volgorde als CONCEPTEN. Per woord: (woord, uitspraak voor Nederlandse kinderen).
# De uitspraak is indicatief (Nederlandse klanken); laat hem door een moedertaalspreker controleren.

# (id, categorie, emoji, Nederlands)
CONCEPTEN = [
    ("zon", "basis", "☀️", "Zon"), ("maan", "basis", "🌙", "Maan"), ("water", "basis", "💧", "Water"),
    ("vuur", "basis", "🔥", "Vuur"), ("huis", "basis", "🏠", "Huis"), ("goedemorgen", "basis", "👋", "Goedemorgen"),
    ("appel", "basis", "🍎", "Appel"), ("melk", "basis", "🥛", "Melk"),
    ("hond", "dieren", "🐕", "Hond"), ("kat", "dieren", "🐈", "Kat"), ("vogel", "dieren", "🐦", "Vogel"),
    ("vis", "dieren", "🐟", "Vis"), ("geit", "dieren", "🐐", "Geit"), ("paard", "dieren", "🐴", "Paard"),
    ("koe", "dieren", "🐄", "Koe"), ("kip", "dieren", "🐔", "Kip"),
    ("rood", "kleuren", "🔴", "Rood"), ("blauw", "kleuren", "🔵", "Blauw"), ("groen", "kleuren", "🟢", "Groen"),
    ("geel", "kleuren", "🟡", "Geel"), ("zwart", "kleuren", "⚫", "Zwart"), ("wit", "kleuren", "⚪", "Wit"),
    ("oranje", "kleuren", "🟠", "Oranje"), ("paars", "kleuren", "🟣", "Paars"),
    ("een", "nummers", "1️⃣", "Eén"), ("twee", "nummers", "2️⃣", "Twee"), ("drie", "nummers", "3️⃣", "Drie"),
    ("vier", "nummers", "4️⃣", "Vier"), ("vijf", "nummers", "5️⃣", "Vijf"), ("zes", "nummers", "6️⃣", "Zes"),
    ("zeven", "nummers", "7️⃣", "Zeven"), ("acht", "nummers", "8️⃣", "Acht"), ("negen", "nummers", "9️⃣", "Negen"),
    ("tien", "nummers", "🔟", "Tien"),
    ("papa", "familie", "👨", "Papa"), ("mama", "familie", "👩", "Mama"), ("opa", "familie", "👴", "Opa"),
    ("oma", "familie", "👵", "Oma"), ("broer", "familie", "👦", "Broer"), ("zus", "familie", "👧", "Zus"),
    ("tante", "familie", "🧕", "Tante"), ("oom", "familie", "🧔", "Oom"),
]

CATEGORIEEN = [
    ("basis", "Basiswoorden", "Kijk & luister", "📚", "pink"),
    ("dieren", "Dieren", "Leer de dieren", "🐾", "green"),
    ("kleuren", "Kleuren", "Kleurige woorden", "🎨", "yellow"),
    ("nummers", "Nummers", "Tel mee tot 10", "🔢", "purple"),
    ("familie", "Familie", None, "👨‍👩‍👧‍👦", "red"),
]

TALEN = {
    "engels": dict(
        naam="Engels", eigen="English", vlag="🇬🇧", map="engels", prefix="eng", opslag="engels.v1",
        titel="Leer Engels", merk="Engels", groet="Hello!", intro="Leer Engels spelenderwijs. Begin maar!",
        footer="Welcome to English! 🇬🇧", kampioen="English-kampioen!", tts=["en"], tts_fallback="en-GB",
        mms="facebook/mms-tts-eng", status="bron", bron="woordenlijst",
        w=[("Sun", "son"), ("Moon", "moen"), ("Water", "wo-ter"), ("Fire", "faai-er"), ("House", "haus"),
           ("Good morning", "goed mor-ning"), ("Apple", "e-pel"), ("Milk", "milk"),
           ("Dog", "dog"), ("Cat", "ket"), ("Bird", "berd"), ("Fish", "fisj"), ("Goat", "goot"), ("Horse", "hors"),
           ("Cow", "kau"), ("Chicken", "tsjik-ken"),
           ("Red", "red"), ("Blue", "bloe"), ("Green", "grien"), ("Yellow", "je-lo"), ("Black", "blek"),
           ("White", "wait"), ("Orange", "o-rindzj"), ("Purple", "per-pel"),
           ("One", "wan"), ("Two", "toe"), ("Three", "thrie"), ("Four", "for"), ("Five", "faiv"), ("Six", "siks"),
           ("Seven", "se-ven"), ("Eight", "eit"), ("Nine", "nain"), ("Ten", "ten"),
           ("Dad", "ded"), ("Mum", "mom"), ("Grandpa", "grend-pa"), ("Grandma", "grend-ma"),
           ("Brother", "bro-der"), ("Sister", "sis-ter"), ("Aunt", "aant"), ("Uncle", "ong-kel")]),
    "spaans": dict(
        naam="Spaans", eigen="Español", vlag="🇪🇸", map="spaans", prefix="spa", opslag="spaans.v1",
        titel="Leer Spaans", merk="Spaans", groet="¡Hola!", intro="Leer Spaans spelenderwijs. ¡Vamos!",
        footer="¡Bienvenidos al español! 🇪🇸", kampioen="Español-kampioen!", tts=["es"], tts_fallback="es-ES",
        mms="facebook/mms-tts-spa", status="bron", bron="woordenlijst",
        w=[("Sol", "sol"), ("Luna", "loe-na"), ("Agua", "a-gwa"), ("Fuego", "fwe-go"), ("Casa", "ka-sa"),
           ("Buenos días", "bwe-nos die-as"), ("Manzana", "man-sa-na"), ("Leche", "le-tsje"),
           ("Perro", "pe-ro"), ("Gato", "ga-to"), ("Pájaro", "pa-ha-ro"), ("Pez", "pes"), ("Cabra", "ka-bra"),
           ("Caballo", "ka-ba-jo"), ("Vaca", "ba-ka"), ("Gallina", "ga-jie-na"),
           ("Rojo", "ro-ho"), ("Azul", "a-soel"), ("Verde", "ber-de"), ("Amarillo", "a-ma-rie-jo"),
           ("Negro", "ne-gro"), ("Blanco", "blan-ko"), ("Naranja", "na-ran-ha"), ("Morado", "mo-ra-do"),
           ("Uno", "oe-no"), ("Dos", "dos"), ("Tres", "tres"), ("Cuatro", "kwa-tro"), ("Cinco", "sin-ko"),
           ("Seis", "seis"), ("Siete", "sje-te"), ("Ocho", "o-tsjo"), ("Nueve", "nwe-be"), ("Diez", "djes"),
           ("Papá", "pa-pa"), ("Mamá", "ma-ma"), ("Abuelo", "a-bwe-lo"), ("Abuela", "a-bwe-la"),
           ("Hermano", "er-ma-no"), ("Hermana", "er-ma-na"), ("Tía", "tie-a"), ("Tío", "tie-o")]),
    "duits": dict(
        naam="Duits", eigen="Deutsch", vlag="🇩🇪", map="duits", prefix="deu", opslag="duits.v1",
        titel="Leer Duits", merk="Duits", groet="Hallo!", intro="Leer Duits spelenderwijs. Los geht's!",
        footer="Willkommen auf Deutsch! 🇩🇪", kampioen="Deutsch-kampioen!", tts=["de"], tts_fallback="de-DE",
        mms="facebook/mms-tts-deu", status="bron", bron="woordenlijst",
        w=[("Sonne", "zo-ne"), ("Mond", "moont"), ("Wasser", "va-ser"), ("Feuer", "foi-er"), ("Haus", "haus"),
           ("Guten Morgen", "goe-ten mor-gen"), ("Apfel", "ap-fel"), ("Milch", "milch"),
           ("Hund", "hoent"), ("Katze", "kat-se"), ("Vogel", "foo-gel"), ("Fisch", "fisj"), ("Ziege", "tsie-ge"),
           ("Pferd", "pfeert"), ("Kuh", "koe"), ("Huhn", "hoen"),
           ("Rot", "root"), ("Blau", "blau"), ("Grün", "gruun"), ("Gelb", "gelp"), ("Schwarz", "sjvarts"),
           ("Weiß", "vais"), ("Orange", "o-ran-zje"), ("Lila", "lie-la"),
           ("Eins", "ains"), ("Zwei", "tsvai"), ("Drei", "drai"), ("Vier", "fier"), ("Fünf", "fuunf"),
           ("Sechs", "zeks"), ("Sieben", "zie-ben"), ("Acht", "acht"), ("Neun", "noin"), ("Zehn", "tseen"),
           ("Papa", "pa-pa"), ("Mama", "ma-ma"), ("Opa", "oo-pa"), ("Oma", "oo-ma"),
           ("Bruder", "broe-der"), ("Schwester", "sjves-ter"), ("Tante", "tan-te"), ("Onkel", "ong-kel")]),
    "frans": dict(
        naam="Frans", eigen="Français", vlag="🇫🇷", map="frans", prefix="fra", opslag="frans.v1",
        titel="Leer Frans", merk="Frans", groet="Bonjour!", intro="Leer Frans spelenderwijs. Allons-y!",
        footer="Bienvenue en français! 🇫🇷", kampioen="Français-kampioen!", tts=["fr"], tts_fallback="fr-FR",
        mms="facebook/mms-tts-fra", status="bron", bron="woordenlijst",
        w=[("Soleil", "so-lèj"), ("Lune", "luun"), ("Eau", "oo"), ("Feu", "fè"), ("Maison", "mè-zon"),
           ("Bonjour", "bon-zjoer"), ("Pomme", "pom"), ("Lait", "lè"),
           ("Chien", "sjien"), ("Chat", "sja"), ("Oiseau", "wa-zoo"), ("Poisson", "pwa-son"), ("Chèvre", "sjèv-r"),
           ("Cheval", "sje-val"), ("Vache", "vasj"), ("Poule", "poel"),
           ("Rouge", "roezj"), ("Bleu", "blè"), ("Vert", "vèr"), ("Jaune", "zjoon"), ("Noir", "nwar"),
           ("Blanc", "blan"), ("Orange", "o-ranzj"), ("Violet", "vjo-lè"),
           ("Un", "un"), ("Deux", "dè"), ("Trois", "trwa"), ("Quatre", "kat-r"), ("Cinq", "sènk"),
           ("Six", "sies"), ("Sept", "sèt"), ("Huit", "wiet"), ("Neuf", "nuf"), ("Dix", "dies"),
           ("Papa", "pa-pa"), ("Maman", "ma-man"), ("Grand-père", "gran-pèr"), ("Grand-mère", "gran-mèr"),
           ("Frère", "frèr"), ("Sœur", "sur"), ("Tante", "tant"), ("Oncle", "onkl")]),
    "oekraiens": dict(
        naam="Oekraïens", eigen="Українська", vlag="🇺🇦", map="oekraiens", prefix="ukr", opslag="oekraiens.v1",
        titel="Leer Oekraïens", merk="Oekraïens", groet="Привіт!", intro="Leer Oekraïens spelenderwijs. Begin maar!",
        footer="Ласкаво просимо! 🇺🇦", kampioen="Oekraïens-kampioen!", tts=["uk"], tts_fallback="uk-UA",
        mms="facebook/mms-tts-ukr", status="check", bron="",
        w=[("Сонце", "son-tse"), ("Місяць", "mie-sjats"), ("Вода", "vo-da"), ("Вогонь", "vo-gon"),
           ("Будинок", "boe-die-nok"), ("Доброго ранку", "do-bro-go ran-koe"), ("Яблуко", "jab-loe-ko"),
           ("Молоко", "mo-lo-ko"),
           ("Собака", "so-ba-ka"), ("Кіт", "kiet"), ("Птах", "ptach"), ("Риба", "rie-ba"), ("Коза", "ko-za"),
           ("Кінь", "kien"), ("Корова", "ko-ro-va"), ("Курка", "koer-ka"),
           ("Червоний", "tsjer-vo-nie"), ("Синій", "sie-nie"), ("Зелений", "ze-le-nie"), ("Жовтий", "zjov-tie"),
           ("Чорний", "tsjor-nie"), ("Білий", "bie-lie"), ("Помаранчевий", "po-ma-ran-tsje-vie"),
           ("Фіолетовий", "fie-o-le-to-vie"),
           ("Один", "o-dien"), ("Два", "dva"), ("Три", "trie"), ("Чотири", "tsjo-tie-rie"), ("П'ять", "pjat"),
           ("Шість", "sjiest"), ("Сім", "siem"), ("Вісім", "vie-siem"), ("Дев'ять", "de-vjat"), ("Десять", "de-sjat"),
           ("Тато", "ta-to"), ("Мама", "ma-ma"), ("Дідусь", "die-does"), ("Бабуся", "ba-boe-sja"),
           ("Брат", "brat"), ("Сестра", "ses-tra"), ("Тітка", "tiet-ka"), ("Дядько", "djad-ko")]),
}
